#!/bin/bash
# Batch conversion script for CALIPSO LAS to Tiled COPC
# Generated by calipso_las_to_tiled_copc_conversion.ipynb

set -e  # Exit on error

echo "Starting batch conversion of LAS files to Tiled COPC"
echo "===================================================="

# Activate conda environment
source /opt/anaconda3/etc/profile.d/conda.sh
conda activate pdal

# Output directory (from data/ directory to public/data/tiled/)
OUTPUT_DIR="../public/data/tiled"
mkdir -p "$OUTPUT_DIR"

# Define latitude tiles (tile_name:lat_min:lat_max)
TILES=(
  "south:-90:-30"
  "south_mid:-30:0"
  "north_mid:0:30"
  "north:30:90"
)

# Process each LAS file
for las_file in converted_las/*.las; do
    echo ""
    echo "Processing: $las_file"

    # Get base filename without extension
    base=$(basename "$las_file" .las)

    # Process each tile
    for TILE_SPEC in "${TILES[@]}"; do
        TILE_NAME=$(echo "$TILE_SPEC" | cut -d: -f1)
        LAT_MIN=$(echo "$TILE_SPEC" | cut -d: -f2)
        LAT_MAX=$(echo "$TILE_SPEC" | cut -d: -f3)
        LAT_RANGE="${LAT_MIN}:${LAT_MAX}"
        output_file="$OUTPUT_DIR/${base}_tile_${TILE_NAME}.copc.laz"

        # Skip if already exists
        if [ -f "$output_file" ]; then
            echo "  ✓ Tile $TILE_NAME already exists, skipping"
            continue
        fi

        echo "  Creating tile: $TILE_NAME (latitude $LAT_RANGE)"

        # Create temporary PDAL pipeline
        cat > temp_pipeline.json <<EOF
{
  "pipeline": [
    {
      "type": "readers.las",
      "filename": "$las_file"
    },
    {
      "type": "filters.range",
      "limits": "Y[$LAT_RANGE]"
    },
    {
      "type": "filters.stats",
      "dimensions": "X,Y,Z,Intensity"
    },
    {
      "type": "writers.copc",
      "filename": "$output_file",
      "forward": "all",
      "a_srs": "EPSG:4326",
      "scale_x": 0.0001,
      "scale_y": 0.0001,
      "scale_z": 0.001,
      "offset_x": "auto",
      "offset_y": "auto",
      "offset_z": "auto"
    }
  ]
}
EOF

        # Run PDAL
        pdal pipeline temp_pipeline.json

        # Get file size
        size=$(du -h "$output_file" | cut -f1)
        echo "  ✓ Created: $output_file ($size)"

        # Clean up
        rm temp_pipeline.json
    done

    echo "  ✅ Complete: $base (4 tiles created)"
done

echo ""
echo "===================================================="
echo "Batch conversion complete!"
echo "Tiled COPC files saved in: $OUTPUT_DIR/"
echo "===================================================="
